POST http://localhost:3000/api/bids HTTP/1.1
Content-Type: application/json

{
  "tender": "test_tender",
  "client": "test_client",
  "alias": "test_alias",
  "bid_date": "21-06-2023",
  "bid_folder_url": "test_folder_url",
  "status": "in-progress",  
  "feedback": {
    "description": "test_description",
    "url": "test_url"
  }
}