POST http://localhost:8080/api/bids HTTP/1.1
Content-Type: application/json

{
  "tender": "Business Intelligence and Data Warehousing",
  "client": "Office for National Statistics",
  "bid_date": "23-06-2023",
  "alias": "ONS",
  "bid_folder_url": "https://organisation.sharepoint.com/Docs/dummyfolder",
  "feedback": {
    "description": "Feedback from client in detail",
    "url": "https://organisation.sharepoint.com/Docs/dummyfolder/feedback"
  },
  "success": [
    {
      "phase": 1,
      "has_score": true,
      "score": 28,
      "out_of": 36
    }
  ],
  "failed": {
      "phase": 2,
      "has_score": true,
      "score": 20,
      "out_of": 36
    }
}
