DELETE  http://localhost:8080/api/bids/643b0628-9d10-4174-af0a-4726eb5125b6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bGlvIiwiYWRtaW4iOnRydWUsImV4cCI6MTY5MjgwMDIzOX0.YWYhaXsrB2RD-TOWifZmCuGrmdlVwpBCXNZZznsY_1U
