GET http://localhost:8080/api/bids/db283b7c-9ae8-4453-a0d6-c2cb0d89e563/questions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBpcmEiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjkxNTg4NzAyfQ.xTrdupUL7LXt3TRO1EmtMA9M7k-Dt4OfW3RW3qwV3sw
X-API-Key: THIS_IS_THE_API_KEY