POST http://localhost:8080/api/bids/66fb5dba-f129-413a-b12e-5a68b5a647d6/questions HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bGlvIiwiYWRtaW4iOnRydWUsImV4cCI6MTY5MTU3MDIyNn0.93o-R3VGeNHAbfthiJ4odsA8n9eBu7ZKwU2KP06EE6E

{
  "description": "This is a question",
  "question_url": "https://organisation.sharepoint.com/Docs/dummyfolder",
  "feedback": {"description": "Good feedback",
  "url": "https://organisation.sharepoint.com/Docs/dummyfolder"}
}
