PUT http://localhost:8080/api/bids/db283b7c-9ae8-4453-a0d6-c2cb0d89e563/questions/75ba8153-6586-4012-9bdd-de63fe0ccde7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciBNY1Rlc3RmYWNlIiwiYWRtaW4iOmZhbHNlfQ.Dg7f8LVtALYWvjZH31re5C-Pc6Hp6Ra-U4LAy0ZQQ9M

{
  "description": "This is a question 4",
  "question_url": "https://organisation.sharepoint.com/Docs/dummyfolder",
  "feedback": {"description": "Good YeI!",
  "url": "https://organisation.sharepoint.com/Docs/dummyfolder"}
}
