POST http://localhost:8080/api/bids/be15c306-c85b-4e67-a9f6-682553c065a1/questions HTTP/1.1
Content-Type: application/json

{
  "description": "This is a question",
  "question_url": "https://organisation.sharepoint.com/Docs/dummyfolder",
  "feedback": {"description": "Good feedback",
  "url": "https://organisation.sharepoint.com/Docs/dummyfolder"}
}
