PUT http://localhost:8080/api/bids/be15c306-c85b-4e67-a9f6-682553c065a1/status HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBpcmEiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjkyODk0MDI3fQ.uK4mM-pXleWPq0py57bvujb6ViKFoTbdQKbsCT8fvdU
Content-Type: application/json

{
  "status": "in_progress"
}