# ---
openapi: 3.0.3
# --------------------------------------------
# Info
info:
  title: Bids API
  description: | 
    This is a API for the Bids API.
    You can find out more about
    this API at [GitHub](https://github.com/methods/tdse-accessForce-bids-api).
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
    Some useful links:
    - [API repository](https://github.com/methods/tdse-accessForce-bids-api)
  version: 1.0.0
  termsOfService: 'https://github.com/methods/tdse-accessForce-bids-api'
  contact:
    email: accessForce@example.com
  license:
    name: MIT License
    url: 'https://github.com/methods/tdse-accessForce-bids-api/blob/develop/LICENSE.md'
# --------------------------------------------
# Server
servers:
  - url: 'http://localhost:3000/api/'
    description: Local server
# --------------------------------------------
# Tags
tags:
  - name: bids
    description: Everything about BIDS
    externalDocs:
      description: Find out more
      url: example.com
  - name: questions
    description: Everything about QUESTIONS
    externalDocs:
      description: Find out more
      url: example.com
# --------------------------------------------
# Paths
paths:
  /bids:
# --------------------------------------------
    get:
      tags:
        - bids
      summary: Returns all bids
      description: Returns all bids
      responses:
        '200':    # status code
          description: A JSON array of bids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bid'
# --------------------------------------------
    post:
      tags:
        - bids
      summary: Create a new bid
      description: Create a new bid
      operationId: post_bid
      requestBody:
        $ref: '#/components/requestBodies/Bid'        
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
# --------------------------------------------
# Components
components:
# --------------------------------------------
# Schemas
  schemas:
    Bid:
      description: Bid document
      type: object
      required:
        - id
        - tender
        - client
        - bid_date
        - status
        - links
        - last_updated
      properties:
        tender:
          type: string
          example: 'Business Intelligence and Data Warehousing'
        bid_folder_url:
          type: string
          example: 'https://organisation.sharepoint.com/Docs/dummyfolder'
        last_updated:
          type: string
          example: "2023-06-27T14:05:17.623827"
        failed:
          type: object
          $ref: '#/components/schemas/Phase'
          example: '#/components/schemas/Phase'
        feedback:
          type: object
          $ref: '#/components/schemas/Feedback'
        success:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/Phase'
        alias:
          type: string
          example: 'ONS'
        client:
          type: string
          example: 'Office for National Statistics'
        links:
          type: object
          required:
            - questions
            - self
          properties:
            questions:
              $ref: '#/components/schemas/QuestionsLink'
            self:
              $ref: '#/components/schemas/SelfLink'
        id:
          type: string
          format: uuid
          example: "UUID('471fea1f-705c-4851-9a5b-df7bc2651428')"
        bid_date:
          type: string
          format: ISO-8601
          example: '2023-06-21T00:00:00'
        status:
          type: string
          description: Bid Status
          example: in_progress
          enum:
            - IN_PROGRESS
            - DELETED
            - COMPLETED
        was_successful:
          type: boolean
          example: true
# --------------------------------------------
    Phase:
      description: Phase information
      type: object
      required:
        - phase
        - has_score
      properties:
        phase:
          description: Phase of bid
          type: integer
          example: 2
        score:
          description: Score achieved at phase
          type: integer
          example: 22
        has_score:
          description: Score information available or not
          type: boolean
          example: true
        out_of:
          description: Maximum score
          type: integer
          example: 36
# --------------------------------------------
    Feedback:
      description: Feedback from client (if provided)
      type: object
      required:
        - feedback_url
        - feedback_description
      properties:
        feedback_url:
          description: Link to feedback
          type: string
          example: 'https://organisation.sharepoint.com/Docs/dummyfolder/feedback'
        feedback_description:
          description: Summary of feedback
          type: string
          example: 'Feedback from client in detail'
# --------------------------------------------
    QuestionsLink:
      description: A link to a collection of questions for a bid
      type: string
      example: 'https://localhost:3000/api//bids/96d69775-29af-46b1-aaf4-bfbdb1543412/questions'
# --------------------------------------------
    SelfLink:
      description: A link to the current resource
      type: string
      example: 'https://localhost:3000/api/bids/471fea1f-705c-4851-9a5b-df7bc2651428'
# --------------------------------------------
    BidRequestBody:
      type: object
      required:
        - tender
        - client
        - bid_date
      properties:
        tender:
          description: Name of tender
          type: string          
        bid_folder_url:
          description: Link to bid info
          type: string        
        feedback:
          description: Feedback info
          type: object
          $ref: '#/components/schemas/Feedback'        
        client:
          description: Name of client tendering
          type: string
        alias:
          description: Client alias
          type: string
        bid_date:
          description: Date of bid
          type: string
        failed_phase:
          description: Failed phase info
          type: object
          $ref: '#/components/schemas/Phase'
        success_list:
          description: List of successful phases
          type: array
          items:
            $ref: '#/components/schemas/Phase'
# --------------------------------------------
# Request bodies
  requestBodies:
    Bid:
      description: Bid object to be added to collection
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BidRequestBody'
          examples:
            200 Created:
              summary: 200 Created
              value:
                tender: 'Business Intelligence and Data Warehousing'
                bid_folder_url: 'https://organisation.sharepoint.com/Docs/dummyfolder'
                feedback:
                  feedback_url: 'https://organisation.sharepoint.com/Docs/dummyfolder/feedback'
                  feedback_description: 'Feedback from client in detail'
                client: 'Office for National Statistics'
                alias: 'ONS'
                bid_date: '21-06-2023'
            400 Bad Request:
              summary: 400 Bad Request
              value:
                bid_folder_url: 'https://organisation.sharepoint.com/Docs/dummyfolder'
                feedback:
                  feedback_url: 'https://organisation.sharepoint.com/Docs/dummyfolder/feedback'
                  feedback_description: 'Feedback from client in detail'
                client: 'Office for National Statistics'
                alias: 'ONS'
                bid_date: '21-06-2023'
# --------------------------------------------
# Error responses
  responses:
    BadRequest:
      description: Bad Request Error
      content:
        text/plain:
          schema:
            type: string
            example: Missing mandatory field
    InternalServerError:
      description: Internal Server Error
      content:
        text/plain:
          schema:
            type: string
            example: Could not connect to a database
# --------------------------------------------